### ISSUE TITLE
Display proper Title in Search Results

### ISSUE THREAD

**Issue by derekfidler** [ShelterTechSF/askdarcel-web#105]
Currently displays a resource's first service title regardless of whether it matches the category.

**Comment by jjfreund** [comment]
Relevant service should be displayed

**Comment by twolfe2** [comment]
Given the data we have now, it doesn't appear there is a way to accurately display the correct service given the category. 
<img width="740" alt="cursor_and_ask_darcel" src="https://cloud.githubusercontent.com/assets/13949747/22814665/3c4a68ca-ef0a-11e6-994e-0bcf7ba909b7.png">

I could write a function that will parse all of the strings for words related to the category but I don't think this would be robust in the long run.

@derekfidler What are your thoughts on placing the name of location as the main header and then having all of the services listed as a sub header separated by '|'s like so:

Desktop:
<img width="651" alt="cursor_and_ask_darcel" src="https://cloud.githubusercontent.com/assets/13949747/22814782/1a7a0bf0-ef0b-11e6-9b7e-bc4fe3ad385b.png">

Mobile:
<img width="260" alt="cursor_and_ask_darcel" src="https://cloud.githubusercontent.com/assets/13949747/22814788/29869a6e-ef0b-11e6-9abd-cd1b0c8513be.png">

**Comment by jjfreund** [comment]
We can determine the correct service to display. There is a second table, categories_services, which associates specific services with a category. You could order (or restrict) the results 
based on the categorization of each service.

We aren't currently populating that table. Let me see if the data is available in the link sf import; if not populating this data will have to be a manual process.

**Comment by jjfreund** [comment]
Did you get a chance to verify that the data I added was sufficient to be able to determine the right service to display?

**Comment by twolfe2** [comment]
Data is sufficient. 

This is what it should look like correct?
<img width="998" alt="cursor_and_ask_darcel" src="https://cloud.githubusercontent.com/assets/13949747/23243704/8884241c-f935-11e6-8593-8510a7beb323.png">
