### ISSUE TITLE
Set up Prettier

### ISSUE THREAD

**Issue by richardxia** [ShelterTechSF/askdarcel-web#1176]
It's 2022, so we should be using a code formatter to avoid any debates about code style. [Prettier](https://prettier.io/) is popular, and I've enjoyed using it in the past.

We should set up Prettier such that it is checked during CI. We may need to disable some ESLint rules, both ones coming from the Airbnb preset and the ones we've set ourselves, since they may conflict with Prettier. If we wanted to reference an existing project, the https://github.com/ShelterTechSF/sheltertech.org project has Prettier, ESLint, and TypeScript set up, so we can look at how it gets all three tools playing nicely together.

**Comment by schroerbrian** [comment]
Completed
