### ISSUE TITLE
Add Report Street Crisis button to navigation

### ISSUE THREAD

**Issue by richardxia** [ShelterTechSF/askdarcel-web#1241]
We'd like to add a new button to our navigation bar that will link to a page on the City of SF's web page for reporting street crises. We have a [Figma design](https://www.figma.com/file/0X2KzS0qDEfZPRRm0TQyd5/SFSG-Website?node-id=4387-4418&t=L1YwscbEQir8JkuG-4) of the UI for both desktop and mobile:

<img width="769" alt="Screen Shot 2023-03-08 at 8 59 39 PM" src="https://user-images.githubusercontent.com/1002748/223923953-eb1240c3-7a16-43de-a4e2-b4e6cc144437.png">

The button should take you to https://sf.gov/information/reporting-concerns-about-street-crises-and-conditions. One thing to note here is that the footer is also being updated with this link as well, with a new "Resources" column on the right-hand side.

Also, this should only display on the non-whitelabeled SF Service Guide site and none of the whitelabeled sites, so we should add a whitelabel property for it.

**Comment by tpetersen0308** [comment]
@richardxia should the button open a new tab? Also, can you point me to a code example of the whitelabel property?

**Comment by tpetersen0308** [comment]
> @richardxia should the button open a new tab? Also, can you point me to a code example of the whitelabel property?

Think I found the whitelabel utils

**Comment by richardxia** [comment]
Re: opening in a new tab, I think probably yes, but let's ask our designers, especially since a parallel project they're working on is accessibility, and I think the choice of behavior may impact accessibility. Could you leave a comment/question on the Figma document?

And as for the whitelabel stuff, I assume you probably found it, but just in case you didn't it's all here: https://github.com/ShelterTechSF/askdarcel-web/blob/a23f28d59961e09483f926cacdd6d988202b9e95/app/utils/whitelabel.ts

The idea is that we centralize all questions that are whitelabel-site-specific into that file, and all other parts of the codebase are only allowed to ask the Whitelabel object about site-specific behavior.

**Comment by tpetersen0308** [comment]
Thanks, I'll check in with them! I opened a PR #1245

**Comment by schroerbrian** [comment]
Done
