### ISSUE TITLE
Remove Feedback feature

### ISSUE THREAD

**Issue by richardxia** [ShelterTechSF/askdarcel-web#1267]
The Feedback feature is a series of forms available on any service page, allowing users to provide a thumbs up/thumbs down vote along with an optional free form text field. It was intended to capture individual user feedback on services, but has not been widely used, and it is not the easiest to discover field in the first place.

To simplify the application, we've decided to remove the Feedback feature. For the frontend application, this will mostly consist of removing all the code in [app/components/listing/feedback](https://github.com/ShelterTechSF/askdarcel-web/tree/aeb64b4050198a4de0d73f7e5ec5d0e9fe162e32/app/components/listing/feedback), as well as modifying any code that references it.

**Comment by schroerbrian** [comment]
Done!
