### ISSUE TITLE
Breaking News URLs get erased when scheduled to publish on a later date

### ISSUE THREAD

**Issue by richardxia** [ShelterTechSF/askdarcel-web#1311]
This was reported by Tammy.

Action prior to dysfunction: Created scheduled Breaking News Article with effective date and priority #.

Action after schedule effective date: Effective date Article was live however URL was deleted as was the URL in the Breaking News Article of the priority article that New Article replaced. (2 urls disappeared from 1 entered/saved and 1 alive/published.

System used is Windows 10 v: 22H2
Browser: Chrome v:119.0.6045.124

Note that publishing live, without a future scheduled date, appears to correctly publish the URLs.

**Comment by schroerbrian** [comment]
done!
