### ISSUE TITLE
Why is there "time" in the url for an organisation?

### ISSUE THREAD

**Issue by hichamsab** [ShelterTechSF/askdarcel-web#132]

**Comment by twolfe2** [comment]
This was a quick hack I did so that we didn't need to make an API call to Google when switching between the resource list view and the resource. 

Once we fully integrate Redux this will go away

**Comment by lgarofalo** [comment]
Now that we are using redux, is this a simple fix? @twolfe2 @achadha

**Comment by jjfreund** [comment]
This was resolved a while ago.
