### ISSUE TITLE
Dashboard Page

### ISSUE THREAD

**Issue by richardxia** [ShelterTechSF/askdarcel-web#1321]
This is just to have the basic dashboard page, but this does _not_ include either the Advance Search component or the Bookmarks. UI-wise, this can just be a blank page for now, but it should replace the Home Page when you're logged in.

Figma link (for reference, since we won't implement much on the page for now): https://www.figma.com/file/XUttHGa1csIpbSiurbYmjo/Case-Worker?type=design&node-id=7164-2799&mode=design&t=IVgzgf3eRrcoQVnd-4

More details in the [Feature Requirements Doc](https://docs.google.com/document/d/1XsgVEfRH9zn4XMQlhtqgfhaJAoL8TV8F6yNlLFa2MA4/edit#bookmark=id.or2snq786dqd)

**Comment by schroerbrian** [comment]
This feature should also include logic that prevents users from accessing the page; bote: this logic could/should be used across different pages in the future
