### ISSUE TITLE
Manage Bookmarks UI

### ISSUE THREAD

**Issue by richardxia** [ShelterTechSF/askdarcel-web#1323]
This covers the UI for managing a user's collection of bookmarks on the Dashboard page.

Figma: https://www.figma.com/file/XUttHGa1csIpbSiurbYmjo/Case-Worker?type=design&node-id=7167-8092&mode=design&t=hcGEvgxPwD4YO79c-4

More details in the [Feature Requirements Doc](https://docs.google.com/document/d/1XsgVEfRH9zn4XMQlhtqgfhaJAoL8TV8F6yNlLFa2MA4/edit#bookmark=id.s2xlzejicluu)

**Comment by schroerbrian** [comment]
The manage bookmarks slider is functional and basic layout is complete; however, many of the features on the slider need to be completed, included:

- drag and drop ability
- text search for bookmarks
- adding new bookmarks from the slider (rather than from a search result)
- creating new folders from the slider
- deleting folders/bookmarks

**Comment by richardxia** [comment]
> adding new bookmarks from the slider (rather than from a search result)

@schroerbrian, I don't think I actually see anything in the Figma mockups that suggests that this should be possible. I think it might be quite challenging to do this, since it would essentially mean that we'd need to embed a miniature version of our search results page into the bookmark slider modal. Could you confirm?

Also, I think I'm going to close out this ticket and split it up into separate tickets for each of the bullet point items you listed, since I think each of them could be implemented separately.

**Comment by richardxia** [comment]
Closing this in favor of split out tickets:

- https://github.com/ShelterTechSF/askdarcel-web/issues/1386
- https://github.com/ShelterTechSF/askdarcel-web/issues/1387
- https://github.com/ShelterTechSF/askdarcel-web/issues/1390
- https://github.com/ShelterTechSF/askdarcel-web/issues/1388
- https://github.com/ShelterTechSF/askdarcel-web/issues/1389

But thanks again for working on the pieces that we've shipped as part of the MVP!

**Comment by schroerbrian** [comment]
Oh yes I agree I’m not sure what I was saying/thinking there - maybe I got it confused with folders. Thanks for breaking up the ticket anyhow!
