### ISSUE TITLE
Save Search Query UI

### ISSUE THREAD

**Issue by richardxia** [ShelterTechSF/askdarcel-web#1325]
This covers the UI on the search results page for saving a search query, along with the saved search queries list on the Dashboard page.

Figma (search results save button): https://docs.google.com/document/d/1XsgVEfRH9zn4XMQlhtqgfhaJAoL8TV8F6yNlLFa2MA4/edit#bookmark=id.pz38eownq5ro

Figma (dashboard saved searches): https://www.figma.com/file/XUttHGa1csIpbSiurbYmjo/Case-Worker?type=design&node-id=7167-8092&mode=design&t=8ZOTl2XXXJDEQmdN-4

More details in the [Feature Requirements Doc](https://docs.google.com/document/d/1XsgVEfRH9zn4XMQlhtqgfhaJAoL8TV8F6yNlLFa2MA4/edit#bookmark=id.pz38eownq5ro).

**Comment by schroerbrian** [comment]
Clicking on "Save Search" button updates button text to say "Results Saved!"

**Comment by schroerbrian** [comment]
Dashboard is more or less done. The only major UI task is to add the Save Search button on the Results page
