### ISSUE TITLE
Search Results Misc Enhancements

### ISSUE THREAD

**Issue by richardxia** [ShelterTechSF/askdarcel-web#1326]
This covers miscellaneous quality of life improvements related to search. It includes expanding and collapsing search result items.

Figma: https://www.figma.com/file/XUttHGa1csIpbSiurbYmjo/Case-Worker?type=design&node-id=7167-6972&mode=design&t=hcGEvgxPwD4YO79c-4

Details in [Feature Requirements Doc](https://docs.google.com/document/d/1XsgVEfRH9zn4XMQlhtqgfhaJAoL8TV8F6yNlLFa2MA4/edit#bookmark=id.bqjzk2i0i8n2)

**Comment by schroerbrian** [comment]
One question I have about this is how the sidebar will work, namely it being organized as groups of  eligibilities with parent eligibility headers. Our current sidebar refinements are returned by Algolia. I'm not sure if we'll be able to integrate this design with the Algolia instantsearch components that we are using very easily
