### ISSUE TITLE
Search by location

### ISSUE THREAD

**Issue by richardxia** [ShelterTechSF/askdarcel-web#1331]
This covers the ability to filter search results by location, via dragging the Google Maps widget.

Figma: https://www.figma.com/file/XUttHGa1csIpbSiurbYmjo/Case-Worker?type=design&node-id=7167-6972&mode=design&t=hcGEvgxPwD4YO79c-4

Details in [Feature Requirements Doc](https://docs.google.com/document/d/1XsgVEfRH9zn4XMQlhtqgfhaJAoL8TV8F6yNlLFa2MA4/edit#bookmark=id.bqjzk2i0i8n2)

**Comment by schroerbrian** [comment]
I believe that our Map library may support this out of the box
