### ISSUE TITLE
'Add Bookmark' Button on a Resource (from SRP) UI

### ISSUE THREAD

**Issue by katerina-kossler** [ShelterTechSF/askdarcel-web#1333]
**Acceptance:** Button with `Add Bookmark` button on each expanded result on a search results page (SRP).

**Design notes:** [figma](https://www.figma.com/file/XUttHGa1csIpbSiurbYmjo/Case-Worker?type=design&node-id=7167-7340&mode=design&t=RGuu2jRvTEVzdSlS-0)

**Notes:**
- two states before and after bookmarking: `Add Bookmark` and `Bookmark Added`
- might want to wait for Modal and API so we can hook up functionality.

**Open Questions:**
- figma suggests no bookmark removal from this view; @richardxia is following up with Research/Design teams to see if we want to support that

**Comment by nayanpaa** [comment]
My team would be interested in taking this project, as well as helping hook up functionality

**Comment by richardxia** [comment]
Closing, since this was implemented by https://github.com/ShelterTechSF/askdarcel-web/pull/1346 and https://github.com/ShelterTechSF/askdarcel-web/pull/1366.
