### ISSUE TITLE
'Add Bookmark' Modal UI

### ISSUE THREAD

**Issue by katerina-kossler** [ShelterTechSF/askdarcel-web#1334]
**Acceptance:** Button with `Add Bookmark` modal for a resource

**Design notes:** [figma](https://www.figma.com/file/XUttHGa1csIpbSiurbYmjo/Case-Worker?type=design&node-id=7960-7115&mode=design&t=RGuu2jRvTEVzdSlS-0)

**Notes:**
- information resource information (name & website) along with an icon (unclear on if this is a static icon or we can to change based on resource type)
- 'location' from Figma should show user's current saved folders & option to create new folder (new folder would require a name and should be assigned the next order); folders cannot be nested in other folders
- add button: no location is required, bookmark creation on click
- 'notes' section from Figma is not in scope for MVP

**Comment by richardxia** [comment]
Closing, since this was implemented by https://github.com/ShelterTechSF/askdarcel-web/pull/1346 and https://github.com/ShelterTechSF/askdarcel-web/pull/1366.
