### ISSUE TITLE
'Manage Folders' Modal UI

### ISSUE THREAD

**Issue by katerina-kossler** [ShelterTechSF/askdarcel-web#1335]
**Acceptance:** `Manage Folders` modal from the dashboard where a user can change the order of Folders or create a new folder

**Design notes:** [figma](https://www.figma.com/file/XUttHGa1csIpbSiurbYmjo/Case-Worker?type=design&node-id=7714-4087&mode=design&t=aDIcinPiOvaunEkn-0)

**Comment by richardxia** [comment]
Closing this as a duplicate of https://github.com/ShelterTechSF/askdarcel-web/issues/1323
