### ISSUE TITLE
'Manage Bookmarks' Modal UI

### ISSUE THREAD

**Issue by katerina-kossler** [ShelterTechSF/askdarcel-web#1336]
**Acceptance:** `Manage Bookmarks` modal from the dashboard where a user can change the order of Bookmarks in a folder

**Design notes:** [figma](https://www.figma.com/file/XUttHGa1csIpbSiurbYmjo/Case-Worker?type=design&node-id=7714-4148&mode=design&t=tPUKxUkrBZx6DMyV-0)

**Comment by richardxia** [comment]
Closing this as a duplicate of https://github.com/ShelterTechSF/askdarcel-web/issues/1323.
