### ISSUE TITLE
Connect Bookmarks, Saved Searches, and all other applicable features to API

### ISSUE THREAD

**Issue by schroerbrian** [ShelterTechSF/askdarcel-web#1349]
Replace areas of the Navigator feature where there are mock data and/or requests with actual calls to the API once it is implemented. Some areas where this is currently needed:

- Add/manage Saved Searches
- Add/manage Bookmarks
- Probably more things....
-

**Comment by richardxia** [comment]
Completed in https://github.com/ShelterTechSF/askdarcel-web/pull/1366 and https://github.com/ShelterTechSF/askdarcel-web/pull/1368.
