### ISSUE TITLE
Show all filled data fields under a service on the org page

### ISSUE THREAD

**Issue by derekfidler** [ShelterTechSF/askdarcel-web#146]
Added eligibility and fee data to Casa De Las Madres and it didn't appear on the site after admin approval

**Comment by jjfreund** [comment]
Specifically, the following fields should be added to what is displayed for each service if they are not null:

Eligibility
Required_Documents
Fee
Application_Process

**Comment by jjfreund** [comment]
Also, add email when this new field gets merged in.
