### ISSUE TITLE
Clicking Ask Darcel logo to go home causes browser page load

### ISSUE THREAD

**Issue by richardxia** [ShelterTechSF/askdarcel-web#175]
If you click the Ask Darcel logo on the top left, it causes the browser to make a full page load instead of just rendering the home page entirely within React. In addition to being a lot slower, it also has the undesirable effect of causing the user's location to be recomputed, which affects the cacheability of API requests. See https://github.com/ShelterTechSF/askdarcel-api/pull/147#issuecomment-286958850

**Comment by alexanderturinske** [comment]
I'll work on this.
