### ISSUE TITLE
Edit Page minor improvements

### ISSUE THREAD

**Issue by achadha** [ShelterTechSF/askdarcel-web#186]
Good opportunity to use Redux on the page. Should be modified to having a single proposed model being manipulated. When determining the changes to post, do a full compare of the proposed model and the existing model in the DB. 

- Need to better componetize this module in general as well.

**Comment by twolfe2** [comment]
@achadha We're adding the ability to edit proposed changes and am thinking of re writing this using Redux at the same time

**Comment by achadha** [comment]
I also want to do that. Is that something we can do separately, though? Getting bug fixes in for the short term, and I'd rather get the janky architected page deployed with those fixes just to be sure that our workshop sessions go more smoothly. Feel like we should address Redux-ing the page after the current issues in the milestone. Thoughts?

**Comment by Maxastuart** [comment]
Spec: 
https://www.notion.so/sheltertech/Condense-Edit-Page-Implement-redesigned-edit-workflow-7f2debc82e9e496b8609b4c0b23e3ed3
