### ISSUE TITLE
Add check box for "no physical location" when adding/editing resource

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#191]
Should remove the address object when deselected.

**Comment by quanhuynh** [comment]
@jjfreund what should be the behavior? does the address section disappear or do the text boxes just become uneditable?

**Comment by derekfidler** [comment]
I think it would be good to remove the address section for online-only resources. i'm not sure how we display these in the search results though. are they just centered on SF?

**Comment by Maxastuart** [comment]
@quanhuynh whichever is easier for the time being, and make a new ticket if making the boxes disappear remains to be done. 

about derek's query, on the backend if the default doesn't automatically become "San Francisco, CA" let's give them city hall's address? or the library for online access? A later update to make search result ranking not purely based on location is coming.

**Comment by quanhuynh** [comment]
i added the checkbox to remove the address field. currently it just sends an empty address to the backend which is the behavior as if the user didn't put in an address. i will make a ticket to make the default address in the backend city hall's address
