### ISSUE TITLE
Add ID of services and resources to names of services / resources in admin page

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#205]
Each service and resource's name should be displayed with its ID in the database as in:

Glide Memorial Church (12)

**Comment by lexholden** [comment]
An equivalent was done some time ago in the admin page redesign (There is a direct link in a changeRequest that takes you to the resource page). Closing.

Can reopen with we really need to actually list the number, which It used to do but I removed for how cluttered it looked.
