### ISSUE TITLE
Submit change request for Resource Phone Number fails

### ISSUE THREAD

**Issue by lgarofalo** [ShelterTechSF/askdarcel-web#211]
UI tries to invoke 

POST /api/phones/number/change_requests HTTP/1.1" 404 34 "https://www.askdarcel.org/resource/edit?resourceid=142" 

which does not exist, correct URL would be /api/phones/change_requests

**Comment by achadha** [comment]
Is there a way to link this to the other phone issue? I'm already working on that one

**Comment by richardxia** [comment]
I'm closing this because I don't think it's actually occurring anymore (or at least I can't even find that URL in the codebase).
