### ISSUE TITLE
Investigate API documentation generators

### ISSUE THREAD

**Issue by richardxia** [ShelterTechSF/askdarcel-web#231]
I think there are several libraries that help you automatically generate documentation for REST APIs, which would be helpful for decoupling frontend and backend development. A few libraries I found from a quick Google search:

- https://github.com/Apipie/apipie-rails
- https://github.com/zipmark/rspec_api_documentation
- https://github.com/lord/slate

If any of these work out, it'd be really cool to have Travis build the docs automatically and push them to GitHub Pages.

**Comment by Maxastuart** [comment]
moved to askdarcel-api #395
