### ISSUE TITLE
Implement react-hot-loader webpack loader

### ISSUE THREAD

**Issue by lexholden** [ShelterTechSF/askdarcel-web#268]
Current development process is slow, refreshing the page (and often forcing logout) on change.

**Comment by Maxastuart** [comment]
Can a developer tell me if this is still relevant? Please Close if not

**Comment by lexholden** [comment]
It is, yep. Need to find the time to finish it, will smooth our development experience.

**Comment by shadycat** [comment]
@lexholden, is there a key page for flow that you have been developing on where you would like me to test the performance given the hot loader?
