### ISSUE TITLE
Redesigned admin page issues

### ISSUE THREAD

**Issue by richardxia** [ShelterTechSF/askdarcel-web#271]
@jjfreund and I did some manual QA and discovered several bugs in the admin page.

The first big bug is that adding a new or editing an existing phone number, note, or schedule on a Resource or Service creates a change request but the change request is invisible on the Admin page. The Accept All button is still visible, and if you click it, it does make the requested changes, but you can't see what the proposed changes are:

<img width="1013" alt="screen shot 2017-07-13 at 9 39 29 pm" src="https://user-images.githubusercontent.com/1002748/28198668-a9ba7c28-6814-11e7-8fe6-28e960a17b6d.png">

The second bug is that adding a new service (with a schedule) seems to have some CSS issues. It looks like the input fields end up spanning the whole row, pushing the approve and reject buttons all the way to the bottom. There's also this weird right half of a rounded rectangle border that appears to the right of the input label.

<img width="988" alt="screen shot 2017-07-13 at 9 48 44 pm" src="https://user-images.githubusercontent.com/1002748/28198728-2bd112e4-6815-11e7-982e-209485b4177e.png">
<img width="950" alt="screen shot 2017-07-13 at 9 48 50 pm" src="https://user-images.githubusercontent.com/1002748/28198727-2bd10fc4-6815-11e7-96cf-f00beb9bcd6e.png">

**Comment by lexholden** [comment]
Hmm investigating this afternoon. Phone numbers and new services did not exist when I made my changes (or at least the seed data I'm using had no instances of either) so I guess that will explain why I missed it.

As a side point we should probably replace the seed data with the a dump from production or similar, since it's pretty out of date.

**Comment by lexholden** [comment]
Obsolete by the refactor in #280
