### ISSUE TITLE
Admin panel refactor

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#316]
Resurrect the admin panel and make it more usable. @lexholden to provide details.

**Comment by alexanderturinske** [comment]
Duplicate of #280 ?

**Comment by lexholden** [comment]
@alexanderturinske This is the broader epic for the pull #280, there are still outstanding issues - install ZenHub and you can see them.

**Comment by alexanderturinske** [comment]
@lexholden Ah; I understand. Thank you!

**Comment by lexholden** [comment]
Closing this, the merged version satisfies this requirement. Will create separate subissues for the enhancements flagged up in #325
