### ISSUE TITLE
Add frontend tests

### ISSUE THREAD

**Issue by richardxia** [ShelterTechSF/askdarcel-web#317]
We don't have a single line of test for the frontend code. This would help us catch a lot of errors before deploying to staging.

cc @lexholden, since it sounded like he started work on this.

**Comment by Maxastuart** [comment]
Isn’t this the same as epic #412 ?

**Comment by lexholden** [comment]
Nope, this is for unit tests, the other is for e2es. We need to improve our coverage in both.
