### ISSUE TITLE
bundle.js is cached between releases and not invalidated for new code

### ISSUE THREAD

**Issue by lgarofalo** [ShelterTechSF/askdarcel-web#327]
When we do a release, the browser doesn't recognize the release of a new web/bundle.js codebase.

It should probably use some kind of hashing to handle invalidation.

cc @twolfe2 @alexanderturinske , this is probably a high ROI issue.

**Comment by alexanderturinske** [comment]
So the browser has the old web/bundle.js cached and is loading that instead of the new one?

**Comment by lgarofalo** [comment]
Is this still an issue? @twolfe2 might be worth another look
