### ISSUE TITLE
Add "change received" feedback

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#330]
When a change request is submitted, feedback indicating that the change was accepted should be returned to the user.

**Comment by alexanderturinske** [comment]
Similarly, there should a few more things changed on the Edit page:
- a "Cancel Changes" button
- a warning/confirmation modal if a user tries to navigate away from the page Edit page with changes that haven't been saved
- #283 relates to this ticket

**Comment by trucnguyen** [comment]
Should this match the specs @Garance91540 put together here for user story "When I hit submit, the page changes but there's no feedback that it worked" https://sheltertech.quip.com/8duuARDxODjT ? 

cc @derekfidler

**Comment by derekfidler** [comment]
No, I’d prefer to use a toast style notification, as opposed to a modal. A user should not need to take action to remove the notification as garance had it, it would be better if it automatically dismissed.

Sent from my mobile

On Jan 7, 2018, at 14:03, Truc <notifications@github.com> wrote:

Should this match the specs @Garance91540 put together here for user story "When I hit submit, the page changes but there's no feedback that it worked" https://sheltertech.quip.com/8duuARDxODjT ?

cc @derekfidler

**Comment by Garance91540** [comment]
@derekfidler the 2 last wireframes shared on Dec 12 and Nov 29 are toast notifications as suggested. 

https://sheltertech.quip.com/8duuARDxODjT

**Comment by derekfidler** [comment]
My mistake, @garance I didn't see the final mockups when i was on mobile.
I've moved the mockups out of chat and into the document. You can see the
mockups here https://sheltertech.quip.com/8duuARDxODjT


Derek Fidler
Product Lead, ShelterTech
Product Design, Bebo

Follow me on Twitter @derekfidler <http://twitter.com/derekfidler>
www.derekfidler.com
df@derekfidler.com <derek@derekfidler.com>
415.857.0879
