### ISSUE TITLE
Research and address Safari issues

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#331]
At the last datathon we experienced issues submitting change requests in Safari. Research and address these.

**Comment by twolfe2** [comment]
On edit resource, when submit is hit, the app errors out

**Comment by twolfe2** [comment]
I've tested this on Safari Version 11.0.1 and the submit button is working. This must be an issue with older versions of Safari. 

Do we have any insights into what browsers case managers and others will be using? We may need to start investing in a tool like [browserstack](https://www.browserstack.com/) so we can start testing in other browser environments.

@jjfreund Which browsers and versions do we want/need to support?

@richardxia Can what you're doing with selenium also be used to do cross browser testing?

**Comment by richardxia** [comment]
I've ditched Selenium in favor of [TestCafe](http://devexpress.github.io/testcafe/), but yes, we can do cross-browser testing with it.

I actually already signed us up for a (free) open source account on [Sauce Labs](https://saucelabs.com/), which will make it easy to test across multiple browsers and OSs, including mobile. Let me document this on Confluence and then I can share more info with the team. In the mean time, if you want access to it so you can manually test on an older version of Safari, I can invite you to the account.
