### ISSUE TITLE
Add Phone Numbers is borked

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#337]
wahhh

**Comment by richardxia** [comment]
Whoever fixes this should unskip this test: https://github.com/ShelterTechSF/askdarcel-web/blob/c69c1d2ed660194612203d8eb5ac173ab811749e/testcafe/editResource.js#L80

**Comment by twolfe2** [comment]
@jjfreund Does anything still need to be done on the back end for this? 

When I try adding a phone number, it overrides the original.

For example 'Test 2' deletes test and it no longer appears to exist after I click save:
![image](https://user-images.githubusercontent.com/13949747/34654170-b7be5cda-f3ac-11e7-86bb-482e42cf02bb.png)

![image](https://user-images.githubusercontent.com/13949747/34654178-d4c53538-f3ac-11e7-9a74-06ddfeda360a.png)

Here's the request I'm making for the creation of the new number:
![image](https://user-images.githubusercontent.com/13949747/34654192-04f38e30-f3ad-11e7-8e74-d9fb62f98810.png)
