### ISSUE TITLE
Get Directions Link from UI requires "Current Location" working

### ISSUE THREAD

**Issue by lgarofalo** [ShelterTechSF/askdarcel-web#341]
Example: https://www.google.com/maps/dir/Current+Location/37.785151,-122.4114983/@37.7852137,-122.4465176,13z/data=!3m1!4b1!4m2!4m1!3e2

<img width="382" alt="screen shot 2017-12-07 at 8 10 10 pm" src="https://user-images.githubusercontent.com/7418073/33750715-aee8c03a-db8a-11e7-81ac-50f74dbc9323.png">

**Comment by Maxastuart** [comment]
@jjfreund Did you mention during our QA you found this wasn't a full fix?
