### ISSUE TITLE
Parsing of alternative sources of data

### ISSUE THREAD

**Issue by lexholden** [ShelterTechSF/askdarcel-web#343]
There are a bunch of alternate  places we can get useful raw data from, much of which will need to be parsed to fit the AskDarcel Data model. Will create issues within this epic, for now still fleshing it out.

Sources:
- [x] HAP Manual
- [ ] [Ministry of Housing Guide ](http://sfmohcd.org/sites/default/files/Documents/MOH/SF%20Housing%20Resource%20Guide%203.7.17_0.pdf)

**Comment by Maxastuart** [comment]
Closing this because of Service Net partner integration (cc @drcaramelsyrup )
