### ISSUE TITLE
Safari and Firefox don't fully work

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#349]
This is in Derek's Quip board so perhaps it is a real issue after all. Derek, can you provide details?

**Comment by richardxia** [comment]
@derekfidler, can you provide details on how to reproduce the problem? Also, affected versions of Safari and Firefox would be great to help us diagnose.

**Comment by richardxia** [comment]
I've reproduced one error on Safari mobile and am working on a fix now.
