### ISSUE TITLE
Split category listing / search results into Services and Resources

### ISSUE THREAD

**Issue by derekfidler** [ShelterTechSF/askdarcel-web#358]
Spec: https://sheltertech.quip.com/zu5gABtbU0dG

**Comment by twolfe2** [comment]
@derekfidler I've got a few questions about this one:

1. If someone searches for a resource (ie during a datathon) should all of the services related to that resource be displayed, or should we separate the search results into services and resources in that case?

2. Are the designs for the new interface finalized, or should I just use the current interface to display services? 

No problem if the designs aren't finalized yet, as I can start working on reconfiguring the Algolia search first and then move on to the front end refactoring next

**Comment by twolfe2** [comment]
Resources should be ranked higher than services in search results and they will also have a slightly different designed card in the results

**Comment by twolfe2** [comment]
Change it so location is asked for once they hit search and fall back to SF if denied
