### ISSUE TITLE
Blank fields on services are sometimes displayed

### ISSUE THREAD

**Issue by richardxia** [ShelterTechSF/askdarcel-web#373]
<img width="755" alt="screen shot 2018-01-11 at 10 22 24 am" src="https://user-images.githubusercontent.com/1002748/34840279-553e83b8-f6b9-11e7-8c9c-31c5f60b41a8.png">

I've also seen the same thing with Hours on some services. Although we should probably remove blank objects on the backend for things defined on other models (e.g. Notes and ScheduleDays), the frontend also shouldn't display the blank objects at all.

**Comment by Maxastuart** [comment]
still in progress @shadycat ?
