### ISSUE TITLE
Allow for links and whitespace in notes fields

### ISSUE THREAD

**Issue by richardxia** [ShelterTechSF/askdarcel-web#378]
We had a suggestion from a datathon attendee to allow rich text formatting in a notes field so that they can create things like links or have more significant whitespace. The volunteer said he would be comfortable with Markdown, but I am not sure how common knowledge of Markdown syntax is outside of tech.

**Comment by lexholden** [comment]
This should be solved with @trucnguyen 's Markdown feature #498
