### ISSUE TITLE
Resource list view (e.g. `/resources?category_id=1`) shows "Loading..." when host isn't localhost.

### ISSUE THREAD

**Issue by jfhamlin** [ShelterTechSF/askdarcel-web#38]
1. Run `npm run dev`.
2. Point your browser at http://askdarcel.lvh.me:8080/resources?category_id=1.

EXPECTED: The resource list page is rendered as  http://localhost:8080/resources?category_id=1.
ACTUAL: The page remains blank except for "Loading..." in the upper left corner.

**Comment by lelandg559** [comment]
http://askdarcel.lvh.me:8080/api/categories is being redirected to the react homepage and ends up returning html instead of the categories JSON

**Comment by lelandg559** [comment]
devServer: {
    historyApiFallback: true,
    devtool: 'source-map',
    colors: true,
    proxy: {
      '/api/*': {
        target: 'http://askdarcel.lvh.me:3000',
        rewrite: function(req) {
          req.url = req.url.replace(/^\/api/, '');
        }
      }
    }

has to be updated with the new api url

do we want to update to that permanently for dev?
