### ISSUE TITLE
Deactivating a service should not discard unsaved changes to other fields

### ISSUE THREAD

**Issue by richardxia** [ShelterTechSF/askdarcel-web#381]
Feedback from a datathon volunteer.

If you make edits to a resource or its services but then you click the deactivate button for a service, then it redirects you back to the resource page but your other edits to the page are not saved.

**Comment by alexanderturinske** [comment]
I can work on this.

**Comment by alexanderturinske** [comment]
Why would a user make changes to a resource that was then going to be deactivated?

**Comment by richardxia** [comment]
The service is being deactivated, not the resource.

**Comment by alexanderturinske** [comment]
Ah, that makes sense. Should this still be done with the redesign happening?

**Comment by richardxia** [comment]
If it's a simple fix, then I don't see why not. I'm assuming we'll still have several datathons before the redesign is live.

**Comment by cliffcrosland** [comment]
Began working on this, but Richard's OrganizationEditPage refactoring will make this change much simpler to do. 

I will help Richard test out his refactoring PR, and when that PR is in, I'll make the necessary changes to complete this issue.
