### ISSUE TITLE
Allow Environment specific static assets

### ISSUE THREAD

**Issue by lgarofalo** [ShelterTechSF/askdarcel-web#389]
If we were to bundle in, for example, a separate static asset for the askdarcel Logo

Like these from `app/assets/index.js`
```
/* eslint-disable global-require */
const images = {
  background: require('../assets/img/bg.png'),
  logoLarge: require('../assets/img/askdarcel-logo.png'),
  logoSmall: require('../assets/img/logo-small-white@3x.png'),
  algolia: require('../assets/img/search-by-algolia.png'),
  icon,
};
```
Could we make them chosen by use of an ENV variable? The goal might be to have a single built image, but depending on the deployment host, use a different logoLarge etc.

The scope of the work here would be to build the image to contain new assets for the sfgov.org project, and have them used appropriately based on a ENV variable of the host the containers run on.

**Comment by jjfreund** [comment]
These assets include

1) images
2) text
3) use of different css
