### ISSUE TITLE
Confirm all service fields are displayed correctly on resource/service pge

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#420]
The following fields of each service should be displayed:

--Service Name
--Service Description
--Application Process, if not null
--Required Documents, if not null
--Fees, if not null
--Notes, as list
--Service Schedule

**Comment by alexanderturinske** [comment]
There are tests to check for some of these, but not all.

**Comment by alexanderturinske** [comment]
- [ ] Service Name
- [ ] Service Description
- [ ] Application Process, if not null
- [ ] Required Documents, if not null
- [ ] Fees, if not null
- [ ] Notes, as list
- [ ] Service Schedule
