### ISSUE TITLE
Confirm service schedules are displayed correctly on resources page

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#426]
Hours of each service should be displayed under each service subheader, with multiple open and close times displayed per day.

**Comment by derekfidler** [comment]
I reviewed Q Foundation, which is our patient zero for this bug, on staging and still saw some weirdness with the hours. In search results it says open 24 hours, the resource page says open 24 hours up top, followed by "null", but the location component says Call for Hours.

![Screen Shot 2019-08-28 at 13 53 56](https://user-images.githubusercontent.com/2722783/63853694-a95bf280-c99b-11e9-9f37-b5b4c018e446.png)

**Comment by jjfreund** [comment]
This isn't the right issue for a bug -- it's asking for the creation of an automated test to confirm that service schedules are working correctly (see the referenced epic).
