### ISSUE TITLE
Confirm adding resource works

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#427]
New resource added should be immediately viewable, with all new fields correctly added including:

--Name
--Address and included fields
--Phone number (number and service type)
--Website
--Email
--Description
--Hours (including multiple open and close times per day)
--Notes

**Comment by alexanderturinske** [comment]
This ticket can be completed now that submitting a resource now takes the user to the new resource page.

- [ ] Name
- [ ] Address and included fields
- [ ] Phone number (number and service type)
- [ ] Website
- [ ] Email
- [ ] Description
- [ ] Hours (including multiple open and close times per day)
- [ ] Notes

**Comment by alexanderturinske** [comment]
Relates to https://github.com/ShelterTechSF/askdarcel-api/issues/449
