### ISSUE TITLE
Confirm modifying resource fields works

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#428]
Check that all resource fields can be modified, including:

--Name
--Address and related fields
--Phone(s) (number and service type)
--Website
--Email

(Schedule day and note modifications are handled by separate tests)

**Comment by alexanderturinske** [comment]
As of this message, the following are done:
- [x] [Name](https://github.com/ShelterTechSF/askdarcel-web/blob/73c37163e2a04cb76e512b18a9fb4fe6264c5a1b/testcafe/editResource.js#L20)
- [x] [Address and related fields](https://github.com/ShelterTechSF/askdarcel-web/blob/73c37163e2a04cb76e512b18a9fb4fe6264c5a1b/testcafe/editResource.js#L25)
- [x] [Resource phone number](https://github.com/ShelterTechSF/askdarcel-web/blob/73c37163e2a04cb76e512b18a9fb4fe6264c5a1b/testcafe/editResource.js#L65)
- [ ] Resource phone type
- [x] [Website](https://github.com/ShelterTechSF/askdarcel-web/blob/73c37163e2a04cb76e512b18a9fb4fe6264c5a1b/testcafe/editResource.js#L124)
- [x] [Email](https://github.com/ShelterTechSF/askdarcel-web/blob/73c37163e2a04cb76e512b18a9fb4fe6264c5a1b/testcafe/editResource.js#L133)
