### ISSUE TITLE
Confirm adding resource phone number works

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#431]

**Comment by zjipsen** [comment]
I think this test already exists as one of the 4 testcafe tests.

**Comment by alexanderturinske** [comment]
This test has been [automated](https://github.com/ShelterTechSF/askdarcel-web/blob/73c37163e2a04cb76e512b18a9fb4fe6264c5a1b/testcafe/editResource.js#L85). Can it be closed?
