### ISSUE TITLE
Confirm modifying schedule day for service works

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#440]

**Comment by alexanderturinske** [comment]
There is a test for [adding](https://github.com/ShelterTechSF/askdarcel-web/blob/73c37163e2a04cb76e512b18a9fb4fe6264c5a1b/testcafe/service.js#L64) and [deleting](https://github.com/ShelterTechSF/askdarcel-web/blob/73c37163e2a04cb76e512b18a9fb4fe6264c5a1b/testcafe/service.js#L81), so a test just for modifying should a copy/paste/modify from those two examples
