### ISSUE TITLE
Remove navigation warning when creating a new resource

### ISSUE THREAD

**Issue by twolfe2** [ShelterTechSF/askdarcel-web#442]
Right now when you go to [submit a new resource](https://staging.askdarcel.org/resource/new), a modal pops up asking if you are sure you want to navigate away, all changes will be lost. We should remove this warning so we don't make people think that new resource won't be saved:
![image.png](https://images.zenhubusercontent.com/585b4a88b9dc3c622023e4a6/558de8d3-3dcb-4d4a-ac05-6c2574c768f2)

**Comment by akatrent** [comment]
Could not recreate issue in Stage or Production in all browsers.
