### ISSUE TITLE
Clicking links on resource page in Safari takes you to askdarcel.org

### ISSUE THREAD

**Issue by twolfe2** [ShelterTechSF/askdarcel-web#443]
I think we have a compatibility issue with Safari that causes clicking on a resources website to take you to askdarcel.org

![image.png](https://images.zenhubusercontent.com/585b4a88b9dc3c622023e4a6/d7224794-90e8-4dba-92e9-dedb965a788e)

**Comment by akatrent** [comment]
Could not recreate issue in Stage or Production in all browsers.
