### ISSUE TITLE
Add git hooks for linting

### ISSUE THREAD

**Issue by alexanderturinske** [ShelterTechSF/askdarcel-web#448]
People often forget about checking code styling before pushing up a change. Husky (https://github.com/typicode/husky/tree/master) allows for easy set up of precommit and prepush hooks. I am going to install this and set up a precommit hook for linting the project

**Comment by achadha-duetto** [comment]
Is that preferable to putting it in the build process once a change has been pushed to a remote branch?

**Comment by achadha** [comment]
Is this preferable to adding it to Travis or something once the change is pushed up to a remote branch?

**Comment by alexanderturinske** [comment]
I think linting is should happen before the commit gets pushed so that reviewers don't get distracted by those types of errors and can focus on the logic. Also, linting is very fast, so the engineer doesn't have to wait that long for this check.

**Comment by achadha** [comment]
Wasn't so much about time, but dev workflow. Go with whatever people prefer. My thought is just that I like pushing things up into my remote branch constantly as I'm working on stuff and prefer dealing with checkstyles and stuff when I think it's ready for review. Don't know the flow you guys have been using since the last time I did stuff, though.

**Comment by alexanderturinske** [comment]
Oh, sure; I can see that. @richardxia @lexholden @twolfe2, what do y'all think?

**Comment by richardxia** [comment]
I don't know how husky works, but will it work in a setup where `npm` is only installed within the Docker container but not on the host machine? I don't have a strong opinion on how we set up the git hook, but even if it's something that I need to manually set up, it's something I'd only have to do once anyway.

**Comment by alexanderturinske** [comment]
Hmm, I'm not sure if it will work with npm only in docker. In any case, Avneet convinced me that we should put it into our CI.

**Comment by lexholden** [comment]
usually npm is smart enough to find the commands in `{ bin: { ... } }` in local packages and run them as if they were installed globally, so I'm pretty sure it would work.

I usually use [pre-commit](https://www.npmjs.com/package/pre-commit) instead of husky but the effect is the same.
