### ISSUE TITLE
Add new side bar to edit page

### ISSUE THREAD

**Issue by twolfe2** [ShelterTechSF/askdarcel-web#450]
Eventually, the edit experience will be more wizard like, but for now, we are just going to tackle changing the side bar, and have it jump to the different sections of the existing edit page when clicked. 

@alexanderturinske We can probably keep the buttons to add a new service where it exists in the current edit page and not add it to the sidebar for now. Also, programs don't exist yet, so that section can be ignored.

![image](https://user-images.githubusercontent.com/13949747/37323239-ac7167a8-263f-11e8-9a70-bf7a09bf1a99.png)

![image.png](https://images.zenhubusercontent.com/585b4a88b9dc3c622023e4a6/df424365-f803-433b-82c2-66d46ac92441)

**Comment by alexanderturinske** [comment]
I implemented the sidebar for the edit page. Should I also put it into the resource page?

**Comment by alexanderturinske** [comment]
![image](https://user-images.githubusercontent.com/12485238/37491136-0e084a4c-285a-11e8-8794-bd007109bd91.png)

**Comment by derekfidler** [comment]
The sidebar only exists in the edit page, the resource/program/service pages have different designs.

Can adding a service/program be added to the sidebar as per the design?

**Comment by derekfidler** [comment]
Also, we've changed the deactivate button from a button in the sidebar to a dropdown option in the organisation details. It would be good to bring the HAP Verify button from the resource page to this sidebar as well.

**Comment by alexanderturinske** [comment]
Thank you for the clarification.

Per Thomas' comment above, we were going to hold off on adding the add service/program buttons for another commit. I don't even think we have the programs feature in yet.

Dropdown in organization details? Where is that?

I can definitely bring the HAP verify button in.

**Comment by derekfidler** [comment]
RE: Deactivation will now be in a dropdown in the org details...

an image for that is in thomas' original post above. The field says: "Is it still operating? Y/N"

**Comment by alexanderturinske** [comment]
Ah, got it. I'll leave the deactivate button until that drop down is created.

Thanks!

**Comment by twolfe2** [comment]
@alexanderturinske Looks good. If it isn't crazy complex, could you add adding a service to the new sidebar?

**Comment by alexanderturinske** [comment]
@twolfe2 TBH, I didn't think it would be, but in trying to move it into the sidebar I have realized the saving of services and the logic around it is confusing. I have also been led to do a lot of refactoring and I don't think we should put it in this commit as it is becoming complex enough to warrant its own ticket.

**Comment by alexanderturinske** [comment]
Nvm. I'll have a commit up by the end of the meeting tomorrow.

**Comment by alexanderturinske** [comment]
No, never mind. There are some issues with adding the add button in that are taking me way to long to debug. We should get this in without it and add those changes in later.
