### ISSUE TITLE
Create stateless tab view component for search

### ISSUE THREAD

**Issue by twolfe2** [ShelterTechSF/askdarcel-web#458]
Todo:

Create a stateless React component that will be passed the following data via props: `description`, `application_info`, and `schedule`.

The data structure for schedule will be the following:
![image.png](https://images.zenhubusercontent.com/585b4a88b9dc3c622023e4a6/e9c10510-0d1e-4bb2-86f7-2cc61ce1548b)

Mocs can be found here: https://projects.invisionapp.com/d/main#/projects/prototypes/9357621

![image.png](https://images.zenhubusercontent.com/585b4a88b9dc3c622023e4a6/1958a716-a9a5-4f1a-b1d8-ef1b78f12ebe)

I would work off of this branch: twolfe2/services-search 
`git fetch -a`
`git checkout origin twolfe2/services-search`
`git checkout -b akatrent/tab-component`

**Comment by lexholden** [comment]
This was done and merged, closing.
