### ISSUE TITLE
Implement new resource page

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#472]

**Comment by Maxastuart** [comment]
Is this the same as "Make resource page mobile friendly?" On our product roadmap it's the main goal for v1.18 ( https://sheltertech.quip.com/LiR0AvqoNae7/AskDarcel-Roadmap )

**Comment by derekfidler** [comment]
No, the resource page is actually an old design and it should look more
like the service pages. I'll update the designs to include mobile and can
revisit then.
