### ISSUE TITLE
Fix issue with not finding lat/long that is causing resource pages not to load

### ISSUE THREAD

**Issue by lexholden** [ShelterTechSF/askdarcel-web#476]
For whatever reason, some pages have not correctly created lat/long when the resource was added. HAP has gathered a list of these failures: https://quip.com/OSRHAOCOayjl

**Comment by jjfreund** [comment]
It's actually the *address* object that is missing, at least in the cases I saw. Having the front end handle this would address the issue, as well as getting us closer to supporting the concept of orgs without physical addresses.
