### ISSUE TITLE
The resources results page (`/resources?...`) only displays `Loading...` on safari.

### ISSUE THREAD

**Issue by jfhamlin** [ShelterTechSF/askdarcel-web#48]
Tested in Safari on iOS.

**Comment by jjfreund** [comment]
Rumor had it that this bug magically fixed itself, but that seems not to be the case -- I can still reproduce it on my iPhone.

**Comment by achadha** [comment]
We are using the fetch() api, which is not safe. We should look into a fetch polyfill OR replace all usages.
