### ISSUE TITLE
Bugfix Resource's email, website, and description cannot be deleted

### ISSUE THREAD

**Issue by lexholden** [ShelterTechSF/askdarcel-web#482]
Investigate whether we can fix the form or API to accept a blank email (or blank website, or blank description) upon saving resource edits (and see if it happens on any service form fields too). If so, fix it. 

(If not, begin the design process and build api endpoint for delete buttons.)

**Comment by Maxastuart** [comment]
lgtm, checked with https://staging.sfserviceguide.org/resource?id=230
