### ISSUE TITLE
Open / closed status is no longer displaying correctly on search results page

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#499]
Some resources/services display as closed though they are open, and some display as open though they are closed.

**Comment by twolfe2** [comment]
Example: 
![image](https://user-images.githubusercontent.com/13949747/41388354-6bedb214-6f40-11e8-8d3a-8dd82cdc9bb9.png)

**Comment by lexholden** [comment]
I commented this out for now, but the RelativeOpeningTimes component needs to be fixed to accurately display times

**Comment by lexholden** [comment]
I'll do this in the next milestone

**Comment by jjfreund** [comment]
This is still returning incorrect results intermittently -- for example, this resource:

https://www.askdarcel.org/resource?id=130

Is said to be "Closed Until Tomorrow" at 2pm on Sunday even though it is open until 5pm.
