### ISSUE TITLE
Create a script/tool to check all resources for ones that fail to load.

### ISSUE THREAD

**Issue by lgarofalo** [ShelterTechSF/askdarcel-web#505]
These are mostly due to JS errors due to unexpected data.

For example: https://www.askdarcel.org/resource?id=611 fails to load to due
```
Uncaught (in promise) TypeError: Cannot read property 'latitude' of null
    at Resource.render (bundle.js:4569)
    at bundle.js:5721
```
The goal of this ticket is not to fix the bug, but to let us identify which of these resources are failing to load, so that we are at least "aware" of them.

cc @jjfreund  This is something that would be friendly for newcomers to tackle.

**Comment by bitfinity** [comment]
Hi, I am willing to help with this. 
Couple questions:
1. Do you want an independent tool apart from the testing framework? I.e. selenium webdriver or puppeteer? I could do python scrapy headless chrome as well, but javascript might fit better into this project.
2. Should it detect any javascript errors (not warnings), or just wait for the id="service" element to load with an appropriate timeout and report if it doesn't (or selector of your choice)?
3. How should it get the ids? (file argument with delimiter separated list could work).
--Jim

**Comment by ProLoser** [comment]
Seems like something that can be done using [crashlytics](http://try.crashlytics.com/)

I think bad address input should be validated during input to avoid this specific bug.
