### ISSUE TITLE
Differentiate Google Analytics between MOHCD site and AskDarcel

### ISSUE THREAD

**Issue by lexholden** [ShelterTechSF/askdarcel-web#512]

**Comment by Maxastuart** [comment]
Isn't this in progress @lexholden ?

**Comment by ruochenhuang** [comment]
My assumption is that we need to create a new "property" in GA for SFServiceGuide -- currently we have multiple views as shown below, but those seem to be pulling from the same source.

<img width="385" alt="Screen Shot 2019-04-07 at 12 27 07 AM" src="https://user-images.githubusercontent.com/13371423/55680247-fdbae480-58cb-11e9-8a90-66759d133b57.png">

**Comment by Maxastuart** [comment]
@jjfreund why is this In Review, isn't it in progress? There's other issues attached via Epic

**Comment by ruochenhuang** [comment]
@Maxastuart @jjfreund @lexholden -- this is marked as "Complete" on the AskDarcel roadmap, but I'm still seeing only the AskDarcel property in GA. If we want to accurately track only SFServiceGuide traffic, we need to get this done by launch (April 30). 

Can you keep me updated? Thank you!

**Comment by jjfreund** [comment]
This is in review because @lexholden has a PR up for it...

**Comment by lexholden** [comment]
Closed my PR because a better solution than multiple properties, is multiple views. We can now see:

- Both askdarcel.org and sfserviceguide.org traffic lumped together
- askdarcel.org traffic
- sfserviceguide.org traffic

This only applies since I changed the filter now, but going forward the second 2 view should start to show different numbers.
