### ISSUE TITLE
Ensure MOHCD funded badge shows properly along with HAP certification

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#530]

**Comment by twolfe2** [comment]
It looks like this still might not be on the resource page
![image](https://user-images.githubusercontent.com/13949747/47472970-779b5d80-d7c5-11e8-9330-c824d054ccc5.png)

**Comment by Maxastuart** [comment]
See #824 (MOHCD & HAP want the HAP-verified badges removed)
