### ISSUE TITLE
Services should be able to inherit resource hours

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#532]
Perhaps via an optional check box?

**Comment by derekfidler** [comment]
I think it should be automatically inherited unless changed by a user and we should backfill empty ones. 

In the UI a checkbox that hides the schedule inputs if checked/inherited would be a good solution.

**Comment by twolfe2** [comment]
Add note to edit page saying 'Leave empty to default to this organizations hours'

**Comment by jjfreund** [comment]
This still doesn't work correctly on the front end -- while the resource hours are now part of the service's index record, the front end is not properly displaying them.

**Comment by jjfreund** [comment]
The issue is that open/closed is not displaying correctly on the search results page when a service is supposed to inherit from its parent resource -- this occurs when no schedule days are associated with the service. There are two relevant fields in the Algolia record for the service:

use_resource_schedule --> this is a boolean, set to true when the service's schedule should be rolled up to the resource.

resource_schedule --> the schedule of the parent resource.

The search results page should have conditional logic to use resource_schedule when appropriate.
