### ISSUE TITLE
Adding / editing resource fails silently if there are missing fields

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#534]

**Comment by jjfreund** [comment]
I'll provide the required fields.

**Comment by jjfreund** [comment]
What do you want to the backend to return in this case?

**Comment by derekfidler** [comment]
A 404 page

Sent from my mobile

On Aug 4, 2018, at 23:11, jjfreund <notifications@github.com> wrote:

What do you want to the backend to return in this case?

**Comment by richardxia** [comment]
Summarizing @jjfreund's description of the issue to me from Slack: If attempt to create a new organization/resource and leave out a required field such as address 1, then the page will create a browser alert telling you that there was an issue creating a resource. If you attempt to hit the submit button a second time, the page silently does nothing. This means that if you don't fix the error, then nothing happens, and even if you do correct all errors, it is no longer possible to create a resource. It appears that something in the code gets into a bad state and effectively prevents one from making forward progress.

The intent of this ticket, then, I am assuming is to fix the page such that it is possible to submit again and either get an error message or to successfully submit.

**Comment by jjfreund** [comment]
Yep
