### ISSUE TITLE
Website links under info section don't open

### ISSUE THREAD

**Issue by ProLoser** [ShelterTechSF/askdarcel-web#549]
I scrolled to the bottom of a resource page and clicked on the website. Nothing happens.

**Comment by alexanderturinske** [comment]
I have tried [several resources](https://staging.askdarcel.org/resource?id=50) and it seems to work; can you find a resource where it does not?

**Comment by ProLoser** [comment]
This has been resolved by #556 as #555 was a duplicate of this issue.
