### ISSUE TITLE
"How To Apply" might need auto-hyperlinking

### ISSUE THREAD

**Issue by ProLoser** [ShelterTechSF/askdarcel-web#550]
https://askdarcel.org/resource?id=823#service-1615

There is a link in there that's not clickable. Might be useful to auto-link this field.

**Comment by alexanderturinske** [comment]
One solution is that the service field could support Markdown like the notes field does

**Comment by cliffcrosland** [comment]
Quick update. Tested this out locally. I think it actually works at the moment. Can someone confirm?

Steps:

1. Edit the description for a service, adding a raw URL: `http://www.example.com/a/b/c`. Save changes.

![edit-description](https://user-images.githubusercontent.com/581562/57988081-a5d0db00-7a3e-11e9-9371-d0b37b5f85d9.png)

2. View the description. The link is clickable:

![description](https://user-images.githubusercontent.com/581562/57988086-bed98c00-7a3e-11e9-9ae2-1a2c95fb4f72.png)

**Comment by cliffcrosland** [comment]
Also, Markdown links work too:
```
[Example](http://www.example.com/a/b/c)
```

Renders the link correctly.

**Comment by drcaramelsyrup** [comment]
@cliffcrosland A few weeks ago I pushed a change that should enable markdown for the service descriptions. Perhaps that resolved this issue?
