### ISSUE TITLE
Service Categories are not shown on service page

### ISSUE THREAD

**Issue by ProLoser** [ShelterTechSF/askdarcel-web#551]
I've added categories to the services for this org: https://askdarcel.org/resource?id=799 but the categories don't show up on the info page. Are these just used for data purposes?

**Comment by alexanderturinske** [comment]
@jjfreund @lexholden?

**Comment by Maxastuart** [comment]
@derekfidler should we see categories on resource pages?

**Comment by derekfidler** [comment]
Yes, categories are for improving search, but don't currently have a function within the UI
