### ISSUE TITLE
Cannot change address

### ISSUE THREAD

**Issue by ProLoser** [ShelterTechSF/askdarcel-web#552]
The server returns a 500 error:

https://askdarcel.org/resource/edit?resourceid=805

**Comment by alexanderturinske** [comment]
Can you give me some more steps? I cannot seem to reproduce this.
Changing the address from 601 => 603 works fine

**Comment by ProLoser** [comment]
I can't seem to reproduce this. I think it was due to a geolocation lookup not succeeding. Closing for now.
