### ISSUE TITLE
Markdown parser does not work with Organization and Service descriptions in certain cases

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#570]

**Comment by lexholden** [comment]
This issue needs more info - I can see both the Description box in search results and the description on the organization page have the markdown renderer working. Where is it missing?

**Comment by jjfreund** [comment]
This issue was reported by HAP. Currently, I see the following issues:

1) Bold and perhaps other tags do do not seem to be respected by the organization description on the organization page.

2) Lists, bolding, and perhaps other tags are not respected by the service descriptions on the organization page.

3) Lists, bolding, and perhaps other tags are not respected by the service descriptions in the search results page. Unsure if we should respect them as the limited space might yield strange looking results. 

4) Same as 3), except with org descriptions.

5) The parser is not applied at all to the description text at the bottom of service page, in the section where all other services and their descriptions are displayed.
