### ISSUE TITLE
Add confirmation prompt for "Mark Resource as Verified"

### ISSUE THREAD

**Issue by ProLoser** [ShelterTechSF/askdarcel-web#580]
I accidentally hit the button on https://askdarcel.org/resource?id=109 and don't know what the repercussions are. Can we add a native prompt to give me a second chance of preventing any accidental clicks?

**Comment by chrisco23** [comment]
Is there some kind of configuration needed to even have this option?  As I see no such button...

**Comment by derekfidler** [comment]
This button was removed in a recent release.
