### ISSUE TITLE
Additional service schedule day cannot be deleted

### ISSUE THREAD

**Issue by alexanderturinske** [ShelterTechSF/askdarcel-web#594]
**Steps:**
1. Navigate to a service
2. Edit the service schedule by adding a second time on a day (i.e. two monday times, etcetera)
3. Save the change
4. Edit the service schedule by deleting the second time on a day (i.e. click on the red x next to the day)
  - EXPECTED: On save,  the day does disappear from the schedule on the service page
  - ACTUAL: On save, the day does NOT disappear from the schedule on the service page

So I wrote a test to ensure deleting a schedule day (i.e. for a service there is a schedule, say a user adds a second time of availability on Tuesday, now I want to delete it) works, and it broke. Looking at the code, it looks like our api supports change requests on schedule days (i.e. change the times of open/close), but I am not sure what I should send to the change request for a delete. Currently the code just changes all the times to `null` when a user tries to delete the time, but the row does not get deleted from the db.
Is this by design? Does our api support deleting a schedule day (i.e. if there are two Tuesday times, can I delete one)? If so, what is the api request to make to achieve this? I am digging around in the ruby now, but if someone knows, that would be rad.

Relates #441 
Relates #593 

@lgarofalo @jjfreund

**Comment by azhelle16** [comment]
I'm unable to reproduce this issue.
