### ISSUE TITLE
Add "Discover Basic Needs" block

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#601]
Each of these cards is comprised of static text and an image. Clicking on each image leads to the search results page. The specific search for each card is described in the requirements document linked to the epic.

**Comment by alexanderturinske** [comment]
@greg-han Have you started on this or created the cards? Because I created some for the legal block and you could probably reuse the card component I created there.

**Comment by alexanderturinske** [comment]
Okay, in my legal block commit I set up a reusable component that can be used for this (currently called `LandingPageResourcesBlock`). So once that gets in, this ticket should be very straight forward.

**Comment by alexanderturinske** [comment]
I am now working on this
