### ISSUE TITLE
Add "Shelter / Volunteer Guide" block

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#603]
This section links to static pages. The static content has not yet been provided.

**Comment by alexanderturinske** [comment]
@jjfreund Are there mockups for this yet? I do not see this block on quip or figma

**Comment by derekfidler** [comment]
The content for this is now in development by the casey team. Eta 1 month.

Sent from my mobile

Op 10 mrt. 2019 om 04:37 heeft Alexander Turinske <notifications@github.com> het volgende geschreven:

@jjfreund Are there mockups for this yet? I do not see this block on quip or figma

**Comment by trucnguyen** [comment]
Is this issue to add another section the Landing page and Service pages to link to the Casey materials?

To confirm - should it be styled like the blue banners here for SF's Coordinated Entry Shelter System?
https://www.figma.com/file/H0kD6ZZPhPR2RMyNJHWWeTtI/Web-Client?node-id=0%3A1

**Comment by trucnguyen** [comment]
I see, it's the "Static Callouts Block" here https://sheltertech.quip.com/K0ZMA1vgbxjd/SFServiceGuideorg-Landing-Page-Requirements

I suppose I can start with creating the volunteer one locally.

[Screen Shot 2019-03-10 at 3.59.31 PM.png](https://images.zenhubusercontent.com/56eda1ed6caf56c9d38dfb0a/cf44e84c-d3ce-4733-886a-87e57be3904a)

**Comment by Maxastuart** [comment]
Yes, the Volunteer callout can be made and simply link to sheltertech.org/volunteer

The Youth Homelessness guide is the next one and a little more important, and I expect it in May so I'm reclassifying this as v1.19. ( @trucnguyen in the meantime, if you'd like you can work on v1.18 tagged bugs)

**Comment by trucnguyen** [comment]
Actively working on this and published the WIP branch 
https://github.com/ShelterTechSF/askdarcel-web/tree/603-shelter-volunteer-callout-blocks
<img width="1678" alt="Screen Shot 2019-04-07 at 3 49 33 PM - local banner" src="https://user-images.githubusercontent.com/603887/55690951-d526ff00-594c-11e9-9448-a534934ff560.png">

How do I export the image from Figma and refer to it in the code as a static asset? 
@derekfidler @richardxia @AnnaKalkanis

**Comment by richardxia** [comment]
If you click on the actual image itself in Figma, you can export it.

![export-figma-image](https://user-images.githubusercontent.com/1002748/55692519-b846f780-595d-11e9-8b13-d5444097cdb5.gif)

**Comment by jjfreund** [comment]
Closed this as MOHCD no longer seems to require it -- will reopen if needed.
