### ISSUE TITLE
Add top services section

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#604]
Some services will be flagged as "featured services" via a numeric field, and ordered by that field's value.

TBD which categories will have featured resources that will be displayed in this section.

**Comment by schroerbrian** [comment]
I'm not actually sure what/where the top resources section is in the new design: https://www.figma.com/proto/H0kD6ZZPhPR2RMyNJHWWeTtI/home?node-id=0%3A1&scaling=min-zoom&redirected=1. 

Would someone be able to point me in the right direction with that? Thank you. cc @jjfreund @derekfidler

**Comment by derekfidler** [comment]
The "Top Resources Section" refers to the "Dynamic Resources/Services
Block" in the quip req doc
https://sheltertech.quip.com/K0ZMA1vgbxjd/SFServiceGuideorg-Landing-Page-Requirements

**Comment by Maxastuart** [comment]
This overlaps with a new ticket I was about to make, to improve our search results by showing featured services MOHCD recommends first. Has anyone been in contact with them about their recommendations?

**Comment by derekfidler** [comment]
I think we can hold off on this until after the launch and we start
receiving feedback.

We may want to replace with specific resources that are accessed frequently
or we could use the space to highlight our guides.

**Comment by Maxastuart** [comment]
I agree, this is better implemented at least after we reorder the search results (after we get MOHCDs input on that) and possible after some data on most used/searched. The top services section will probably be just the top search results from each of a few categories, but can be dynamically based on those results.

Putting back on backlog. @schroerbrian still want to own it? (If not, unassign yourself)

**Comment by Maxastuart** [comment]
I'm on this, going to speak to MOHCD in April about what services they frequently recommend. Hopefully, that conversation yields the info for both the Top Services landing page section and better search result ranking.
