### ISSUE TITLE
Hours for service page are cached incorrectly

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#625]
There seems to be a bug where the hours associated with a service are somehow cached between requests. For example, click on the Food category, then click on the second result ("Food Pantry"). The hours are listed as 12-2pm on Saturday. Then click the back button and click on the third result ("Housing & Shelter")*.

The hours are still listed as 12-2pm. Then refresh the page. The hours will now display as 9:30-5:00 on weekdays.

*In case you were wondering, the "Housing & Shelter" service involves housing and a meal which is why it is flagged in the Food category. Arguably it should be decomposed into two services.

**Comment by Maxastuart** [comment]
@lexholden do you have this handled? I’m trying to free old assignees to make tasks that are available to be grabbed visible

**Comment by Maxastuart** [comment]
@lgarofalo
