### ISSUE TITLE
Replace header and footer branding for requests to sfserviceguide.org

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#633]
Branding should conform to Derek's design.

**Comment by Maxastuart** [comment]
I see issues:

- Footer hyperlinks under "About Us" link back to AskDarcel.org instead of ShelterTech.org , and "Email" link is broken too
- Missing link to "Donate" under "About Us"

See Quip, https://sheltertech.quip.com/K0ZMA1vgbxjd/SFServiceGuideorg-Landing-Page-Requirements#YVPACAS7QRy
