### ISSUE TITLE
The map is broken for search results when accessing sfserviceguide.org

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#635]
Requests to www.askdarcel.org function correctly however.

**Comment by jjfreund** [comment]
<img width="1426" alt="screen shot 2019-02-24 at 2 23 11 pm" src="https://user-images.githubusercontent.com/637355/53306326-a4798300-3840-11e9-8832-62355f8153b8.png">

**Comment by AnnaKalkanis** [comment]
This is just a matter of whitelisting `sfserviceguide.org` against our google maps api key.

https://developers.google.com/maps/documentation/javascript/error-messages#referer-not-allowed-map-error

**Comment by AnnaKalkanis** [comment]
@lgarofalo updated the api key to allow for access on `sfserviceguide.org`
