### ISSUE TITLE
Add checkbox to allow a new service to inherit its schedule from its parent resource

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#637]
A new flag is being added to the service object, inherit_schedule, which will determine whether or not it inherits its schedule from its parent resource. Add this field to the add / edit service screen.

**Comment by Maxastuart** [comment]
If this is moved back to to-do, is it also open for reassignment? (feel free to unassign yourself @AnnaKalkanis ) Or is it blocked by a dependency? I reckon it can remain in In Progress if you're happy to do it after a dependency is cleared

**Comment by AnnaKalkanis** [comment]
I moved this back to ‘to do’ because https://github.com/ShelterTechSF/askdarcel-api/issues/176 blocks it. I’m still planning on doing it once that is done, but seemed weird to have it in progress if there’s no actual progress being made on it.
