### ISSUE TITLE
Add <head> metadata on pages related to resources or services

### ISSUE THREAD

**Issue by richardxia** [ShelterTechSF/askdarcel-web#642]
This will greatly help SEO. Titles and descriptions can easily be pulled from the resource and service models in the DB.

**Comment by Maxastuart** [comment]
Here's some example metadata ( https://sheltertech.quip.com/rbbPAkqybe2a/sheltertechorg-Web-Page-Metadata ), whoever grabs this please feel free to create your own for the resource and service pages.
