### ISSUE TITLE
Fix remaining issues with improper open and closed status being displayed

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#647]
I see the following issues still (on 2:12, Sunday):

1) Certain services neither display as open or closed, such as Harm Reduction offered by Temenos Catholic Worker. This service is neither open nor closed, but should be open:
https://www.askdarcel.org/services/1822

2) Certain services are displayed as closed, but remain listed as open when the open filter is clicked -- different logic is used to determine whether they are open. In the following case:
https://www.askdarcel.org/services/94
 I believe it is because the hours are meant to indicate 24 hour availability (11:00pm - 10:59 pm)

<img width="1435" alt="Screen Shot 2019-03-10 at 2 13 15 PM" src="https://user-images.githubusercontent.com/637355/54091727-951a2f80-4340-11e9-93aa-1d5991cbf1b1.png">

**Comment by cliffcrosland** [comment]
This appears to be working great now. @jjfreund Is this ok to close? Thanks!

cc: @Maxastuart 

![Screen Shot 2019-03-27 at 8 09 46 PM](https://user-images.githubusercontent.com/581562/55127132-54eed700-50cc-11e9-8285-ff35d0cc97c9.png)

![Screen Shot 2019-03-27 at 8 10 24 PM](https://user-images.githubusercontent.com/581562/55127147-689a3d80-50cc-11e9-827e-0da65c84ce40.png)

**Comment by Maxastuart** [comment]
Might work, but need the hour-offset fixed to truly test and close

**Comment by Maxastuart** [comment]
#418 #415 related

**Comment by cliffcrosland** [comment]
Relevant PR in askdarcel-api from @jjfreund https://github.com/ShelterTechSF/askdarcel-api/pull/400

**Comment by jjfreund** [comment]
@richardxia's refactor will take care of this -- but not in this milestone.

**Comment by fredciaramaglia** [comment]
Other issues related to this bug:
1) On Friday at 11:15pm, resource Workforce Development Program displayed Open Now when the hours in the details say Friday 8:00am to 5:30pm.  Note: The Open Now button correctly filters out this resource.
2) On Friday at 11:33pm, resource Early Intervention And School-Based Program displayed Closed in 20 minutes when the details say Friday 9:00am to 7:00pm.  Note: The Open Now button correctly filters out this resource.  The same is true for Casa Corazón.
3. On Friday 11:38pm, many resources displayed Closed until tomorrow when they are closed for the weekend and will not reopen until Monday. Should say something like Closed until Monday 9:00am.
