### ISSUE TITLE
Location, sign up, and login for search bar

### ISSUE THREAD

**Issue by Maxastuart** [ShelterTechSF/askdarcel-web#657]
Add location, sign up, and login to search bar as in image below (help button made irrelevant by Intercom): 

![image.png](https://images.zenhubusercontent.com/585b4a88b9dc3c622023e4a6/99f61f08-5f80-4765-9807-56d0ccd57d66)

**Comment by derekfidler** [comment]
We're going to shelve accounts for now and right now we only capture location via browser and don't need to have an extra bar for it. i've updated the comps to reflect this
