### ISSUE TITLE
Service call on "Save Changes" on resource page doesn't work, no updates from datathons or other changes save!

### ISSUE THREAD

**Issue by Maxastuart** [ShelterTechSF/askdarcel-web#661]
[This appears to only be a bug during datathons - possibly due to UpWork's WiFi?] 
Service call on "Save Changes" on resource page doesn't work, no updates from datathons or other changes save! Also the info that was previously saved is not displaying correctly on resources or services (Possibly calling old database version).
Can be seen on any resource.

**Comment by jjfreund** [comment]
How often is this occurring in datathons? For the most part, saving must be working as the datathons are successful...

**Comment by jjfreund** [comment]
@Maxastuart -- if you could provide a specific resource ID and time of failure that would help us dig through the logs.

**Comment by Maxastuart** [comment]
The time was Tues, March 19th 6pm-7pm, and the resource list was here: 
https://docs.google.com/spreadsheets/d/19pi5OAO8jnm6ZsDlrRZO8aoEDTeBBtzHj_z2nuYb1mo/edit#gid=1635839422 
(we saved the info in the next tab on the sheet): 
https://docs.google.com/spreadsheets/d/19pi5OAO8jnm6ZsDlrRZO8aoEDTeBBtzHj_z2nuYb1mo/edit#gid=770941089
