### ISSUE TITLE
Fully Integrate Redux

### ISSUE THREAD

**Issue by Maxastuart** [ShelterTechSF/askdarcel-web#676]
Convert entire application to use Redux

**Comment by Maxastuart** [comment]
We need to flush out what's needed for this refactor and assign parts to people if possible. I think adding component management and testing should be a big priority before we try to change too much more. @richardxia @lexholden @alexanderturinske @twolfe2 @jjfreund

**Comment by jmpainter** [comment]
I'm starting to take a look at this and am willing to take some or all of it on. It would be good to get a strategy on how to proceed with this, maybe one component at a time.
