### ISSUE TITLE
Intercom not working, Firefox on Win7

### ISSUE THREAD

**Issue by Maxastuart** [ShelterTechSF/askdarcel-web#677]
intercom is not working on:
Firefox Quantum 66.0.1 (64-bit)
Windows 7 Professional

Reported by Derek, through Barry from MOHCD

**Comment by Maxastuart** [comment]
I believe this is "Chatbot does not appear in Firefox (at least not for CCSF computers)" from https://sheltertech.quip.com/XgIOAoOLaHLN/MOHCDShelterTech-AgendaMeeting-Notes-April-11-2019 

Double-check that the location of these Windows 7 computers correlates with City College of San Francisco.

**Comment by richardxia** [comment]
I haven't done any research on this, but in general, Firefox is trending towards a privacy-first approach as a product differentiator from other browsers, so it might be the case that this is not "fixable" because Firefox is blocking the Intercom service because it lumps it into the same category of things like user analytics and advertising trackers.

**Comment by Maxastuart** [comment]
I'm on top of getting more info from Barry (MOHCD) on the exact time, computers, Firefox versions, and any firewalls or network oddities involved.

**Comment by jmpainter** [comment]
I asked someone at Intercom about what may be causing this. Here was Lexi's response:

"One of the common reasons the Messenger might not show for some users is if they have an adblocker enabled. While Intercom isn’t an ad-provider, adblocking plugins may also block JavaScript that includes tracking functionality.

You could have them try disabling their adblocker, and if the Messenger still doesn’t load, ask if they can grab a screenshot of any error messages they see in the Javascript console, and we can do some further troubleshooting."

It seems possible that an agency like this could be using an adblocker.
