### ISSUE TITLE
Browser Compatibility (ie11)

### ISSUE THREAD

**Issue by Maxastuart** [ShelterTechSF/askdarcel-web#678]
Let's make the site compatible with some old and varied browsers, right now it's not showing up at all on Internet Explorer 11 and that's a good baseline for now for other compatibility.

**Comment by ruochenhuang** [comment]
Here are the top browsers/versions between March 22 and April 9 --
 
<img width="326" alt="Screen Shot 2019-04-10 at 11 59 32 PM" src="https://user-images.githubusercontent.com/13371423/55937013-c52d4a80-5bec-11e9-8533-9b3be13ef051.png">

**Comment by ruochenhuang** [comment]
people are still using IE8 (lol)
