### ISSUE TITLE
Mobile Friendly Service Page

### ISSUE THREAD

**Issue by Maxastuart** [ShelterTechSF/askdarcel-web#680]
preliminary design from https://www.figma.com/file/H0kD6ZZPhPR2RMyNJHWWeTtI/Web-Client?node-id=0%3A1 (this is a pic of resource page, @derekfidler is working on the service page specifics. Tag or Slack him if questions)
![Screen Shot 2019-03-25 at 22.10.38.png](https://images.zenhubusercontent.com/5c7315ed218687594435a617/a591a710-40bc-4a7d-9f79-b0dad853ccb7)

**Comment by derekfidler** [comment]
I've updated the comps for this to address the issue with sticky footers and mobile safari. You can find the updated comps here: https://www.figma.com/file/H0kD6ZZPhPR2RMyNJHWWeTtI/Web-Client?node-id=1456%3A1472

![Screen Shot 2019-03-26 at 17 08 55](https://user-images.githubusercontent.com/2722783/55014055-a0c94f80-4fea-11e9-9268-7e00fb2aca27.png)

**Comment by AnnaKalkanis** [comment]
https://github.com/ShelterTechSF/askdarcel-web/pull/695
