### ISSUE TITLE
Add Service Net attribution to services and orgs with data improved via Service Net

### ISSUE THREAD

**Issue by derekfidler** [ShelterTechSF/askdarcel-web#682]
Our data partner, Service Net, has requested we provide an attribution for records that have been updated via the Service Net program. 

Attached is an image of what the attribution should look like. It should appear on service and resource pages below the HAP verification attribution.

![Screen Shot 2019-03-27 at 12 09 21](https://user-images.githubusercontent.com/2722783/55076560-0de5ef00-5096-11e9-81b5-83e7386f842f.png)

Comps for this design are in the figma here: https://www.figma.com/file/H0kD6ZZPhPR2RMyNJHWWeTtI/Web-Client?node-id=1458%3A235

The link should go to our Medium article about the program here: https://medium.com/@Shelter_Tech/sheltertech-is-participating-in-the-benetech-service-net-pilot-in-the-san-francisco-bay-area-b28645d3dee6

**Comment by jjfreund** [comment]
This is dependent on: https://github.com/ShelterTechSF/askdarcel-api/issues/405

**Comment by schroerbrian** [comment]
hey @derekfidler @jjfreund – is there a separate ticket for the HAP verification or is that already done? I originally misread this ticket and coded the HAP UI, in addition to the Service Net attribution. If the HAP UI has already been done, I'll tear my code out. If not, I guess this'll just be a two point ticket ;)
