### ISSUE TITLE
Improve Search Front End (Filters)

### ISSUE THREAD

**Issue by Maxastuart** [ShelterTechSF/askdarcel-web#685]
Search Filtering Requirements Doc: 
https://sheltertech.quip.com/WCg2AYLSGVOQ/Search-Filtering-Requirements-Doc 

Mockup: 
https://www.figma.com/file/H0kD6ZZPhPR2RMyNJHWWeTtI/Web-Client?node-id=0%3A1

**Comment by quanhuynh** [comment]
duplicate with #736

**Comment by jjfreund** [comment]
Dupe of 736
