### ISSUE TITLE
Google Analytics -- Add Search Console to Track User Queries

### ISSUE THREAD

**Issue by ruochenhuang** [ShelterTechSF/askdarcel-web#691]
Requesting that we add Search Console into Google Analytics -- we will need to add a TXT record into the DNS Configuration for both SFServiceGuide.org and AskDarcel.org

Here's the page in GA to set it up: 
<img width="1172" alt="Screen Shot 2019-04-07 at 12 48 57 AM" src="https://user-images.githubusercontent.com/13371423/55680492-f8ab6480-58ce-11e9-9409-cb17dfb11fc8.png">

Here's the link to creating the Search Console: https://search.google.com/u/3/search-console/welcome

**Comment by ruochenhuang** [comment]
cc @lexholden @jjfreund @Maxastuart

**Comment by lexholden** [comment]
Added the txt records for both domains, need to wait for them to propagate it seems. Will look in a couple of hours.

**Comment by Maxastuart** [comment]
@lexholden finished I presume?

**Comment by lexholden** [comment]
@Maxastuart  It was done and I left it too long to reverify. Just done now and adding an actual  reminder to recheck when it propagates this time 😄

**Comment by lexholden** [comment]
OK this is now done. @ruochenhuang . Closing the ticket.
