### ISSUE TITLE
Images from google maps api do not appear on search results page

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#70]

**Comment by jjfreund** [comment]
This problem intermittently persists. Oddly enough, I can copy and paste the broken image paths into my browser and view them directly.

**Comment by jfhamlin** [comment]
We often exceed our maps request quota, since we haven't configured a key. They probably use the origin page's hostname to track use; that would explain why it works when pasted directly into your browser location bar.

**Comment by ZanderSparrow** [comment]
Yeah, I think this will be fixed by adding/properly configuring keys on prod

**Comment by lelandg559** [comment]
Request URL:https://maps.googleapis.com/maps/api/streetview?size=400x400&location=37.768532,-122.449086&fov=90&heading=235&pitch=10
Request Method:GET
Status Code:403 OK

The Google Maps API server rejected your request. This service requires an API key.
