### ISSUE TITLE
Add default address for empty addresses

### ISSUE THREAD

**Issue by quanhuynh** [ShelterTechSF/askdarcel-web#704]
For non-physical resources and empty addresses, we should add a default address to city hall or library (and make sure users know the resource doesn't have an address)

**Comment by jason358ma** [comment]
@quanhuynh Could you link to an example of a non-physical resource or empty address?

**Comment by quanhuynh** [comment]
@jason358ma we don't have any in our database afaik. but the possibility is still there that a resource is ran entirely online or is transient in location
right now our backend treats an empty address as an address with null fields, and i'm not sure how that shows up on the map (it may not at all)

**Comment by Maxastuart** [comment]
ShelterTech is an org we could add with no physical address, SFServiceGuide - AskDarcel and ShelterConnect being Services (24hr)
