### ISSUE TITLE
[Algolia] Add Boolean Attribute for MOHCD-Categorized Services

### ISSUE THREAD

**Issue by ruochenhuang** [ShelterTechSF/askdarcel-web#705]
We received a request from MOHCD to surface MOHCD-funded/affiliated resources and services first. This includes the DAHLIA resource page (https://askdarcel.org/resource?id=886). 

Currently, these services are demarcated by a "MOHCD-funded" tag in the Categories attribute. As per discussion with Joe, requesting that we create a "MOHCD" boolean attribute where services/resources categorized as "MOHCD-funded" are "TRUE" and all else are "FALSE".

We can then modify our sorting methodology to have "MOHCD": "TRUE" be prioritized.

Here's the reference: https://www.algolia.com/doc/guides/managing-results/refine-results/sorting/

Example: 

index.set_settings({
  ranking: [
    'desc(MOHCD)',
    [],
    [],
    [],
  ]
})

**Comment by jjfreund** [comment]
Issue moved to [ShelterTechSF/askdarcel-api #410](https://github.com/ShelterTechSF/askdarcel-api/issues/410) via [**ZenHub**](https://www.zenhub.com/)
