### ISSUE TITLE
 Change intercom so that only cartoons and not people show up

### ISSUE THREAD

**Issue by Maxastuart** [ShelterTechSF/askdarcel-web#706]
@derekfidler if you're not too busy could you do this?

**Comment by derekfidler** [comment]
I already removed Ryan Reynolds. I tjink that should be sufficient for now.

Sent from my mobile

Op 19 apr. 2019 om 06:23 heeft Max S <notifications@github.com> het volgende geschreven:

@derekfidler if you're not too busy could you do this?
