### ISSUE TITLE
Create "Submit Feedback" link on the site (besides intercom)

### ISSUE THREAD

**Issue by Maxastuart** [ShelterTechSF/askdarcel-web#707]
Location TBD, but create a link for people to provide feedback on the site (beyond intercom) and link to the same form linked in intercom. @derekfidler any ideas? MOHCD mentioned the bottom of the landing page may suffice, curious where you, @AnnaKalkanis and @lexholden think would be best.

I think this is mostly because Intercom doesn't work or is disallowed on some of the city's computers/networks.

**Comment by jmpainter** [comment]
Would it work to have the link in the footer? Maybe in the 'Feedback' column?

**Comment by jmpainter** [comment]
Sorry, I meant 'Connect' column

**Comment by Maxastuart** [comment]
Bah I botched this review and didn't see Derek asked for it to be in the header. I need to un-do this.

**Comment by Maxastuart** [comment]
fixed, issue superfluous
