### ISSUE TITLE
MOHCD Landing Page Requests

### ISSUE THREAD

**Issue by Maxastuart** [ShelterTechSF/askdarcel-web#710]
https://sheltertech.quip.com/UYCRAw3bQ6KA/-MOHCD-Landing-Page-Requests

**Comment by chrisco23** [comment]
Clicking the link only takes me to sheltertech.quip.com.  From there searching for the file, it shows up as being in the Trash.  Please advise.

**Comment by derekfidler** [comment]
hey @chrisco23 we've moved the product development out of Quip and into Notion. you can find any feature spec docs here: https://www.notion.so/sheltertech/MOHCD-Landing-Page-Requests-659cf432d82946278b8643e47fc70617

@Maxastuart I believe we can close this issue right? it's already been released afaik.

**Comment by chrisco23** [comment]
I see.  Thanks.
