### ISSUE TITLE
Reduce Basic Needs block to 3 items

### ISSUE THREAD

**Issue by Maxastuart** [ShelterTechSF/askdarcel-web#712]
Reduce Basic Needs block to 3 items
    * Apply for shelter (link to guide)
    * Free meals served daily (link to http://www.freeprintshop.org/download/eats_english.pdf)
    * Public toilets and showers (include Pit Stop locations in search results)

**Comment by derekfidler** [comment]
Current:
<img width="1017" alt="Screenshot 2019-06-26 at 19 23 24" src="https://user-images.githubusercontent.com/2722783/60228571-e7c41c80-9847-11e9-9ebe-97e849653e04.png">


Desired result:
<img width="953" alt="Screenshot 2019-06-26 at 19 18 59" src="https://user-images.githubusercontent.com/2722783/60228540-d418b600-9847-11e9-8285-79dfaae2fe12.png">
