### ISSUE TITLE
link to See More in content blocks

### ISSUE THREAD

**Issue by Maxastuart** [ShelterTechSF/askdarcel-web#713]
Include link to “See More” to each content block
    * Display results for that category

https://sheltertech.quip.com/UYCRAw3bQ6KA/-MOHCD-Landing-Page-Requests

**Comment by shadycat** [comment]
Hey, @Maxastuart the quip link in this ticket only links to the sheltertech quip main page for me. Was there an image for what the changes should look like in that doc?

**Comment by derekfidler** [comment]
Quip has been phased out for product development. The new link to this feature spec is here: https://www.notion.so/sheltertech/MOHCD-Landing-Page-Requests-659cf432d82946278b8643e47fc70617

**Comment by Maxastuart** [comment]
Related: make headings link to same results https://github.com/ShelterTechSF/askdarcel-web/issues/796
