### ISSUE TITLE
Move save button or make it floating & fix bug on services list

### ISSUE THREAD

**Issue by Maxastuart** [ShelterTechSF/askdarcel-web#755]
Move save button (or make it floating) on edit page to make it easier to save when a resource has lots of services. (see below comments on the bug)

**Comment by Maxastuart** [comment]
(Notes from the duplicate Joe made: "Save" button should always be visible on the left-hand side of the edit screen. Currently, the "Save" button on the edit screen is anchored to the bottom -- the user must scroll all the way down to access it. The "Save" button should instead always be visible.)

**Comment by quanhuynh** [comment]
Found another issue while working on this one:
The sidebar populates existing services twice, with the duplicates not shown. This makes the Services Section longer than it should be, and when a new service is added, there's a huge gap between existing services and the new service. see screenshot below:

![Screen Shot 2019-07-28 at 3 52 16 PM](https://user-images.githubusercontent.com/8869737/62013959-b04ed580-b14f-11e9-8f56-4c4a705d0dd5.png)

I am going to make a fix for this in the same PR

Fyi @Maxastuart
