### ISSUE TITLE
Create UI for modifying resources and services

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#76]
Build according to Derek's spec.

**Comment by derekfidler** [comment]
I'll have designs and spec for this on Wed 20 Jul. 
@achadha if you do the react, I'll do the css.

**Comment by jjfreund** [comment]
So the spec for this is simple: there should be an edit button on the resource page. Clicking this button will take the page into writeable mode, where each of the resource and its services becomes editable. Clicking save persists the changes to the database. There is not currently a need for role-based authentication for this functionality, though that will be added soon. @derekfidler, are you still going to give us a design for this or should we just do that ourselves?

**Comment by derekfidler** [comment]
if you add contenteditable="true" to all the items that are editable on a resource page i will make a global style class for this in the css. A submit/save button will need to appear on the page at the bottom which I can style too if someone just puts in the basic html.
