### ISSUE TITLE
Service status is incorrect early in the morning

### ISSUE THREAD

**Issue by fredciaramaglia** [ShelterTechSF/askdarcel-web#768]
On Wednesday, 7:54am
Searched for Cooperative Living Apartments 
Status was: Closed Until Tomorrow
Cooperative Living Apartments opens at 9:00am today
Status should be: Closed Now, or even better: Closed Until 9:00am Today

![image.png](https://images.zenhubusercontent.com/5cdcbb3d22376b7717f71776/fa95f3df-7759-4a3a-a49f-ef2cf89181ec)

![image.png](https://images.zenhubusercontent.com/5cdcbb3d22376b7717f71776/47edd3a7-09fb-4c83-9a60-9a65a2f7f2b9)

**Comment by fredciaramaglia** [comment]
Tested again at 7:46am Aug 6 on 1.20 in both staging and production. This bug still occurs and produces the same result.

**Comment by richardxia** [comment]
This looks like was fixed in the previous release, when most of my time refactoring stuff landed. I simulated this test by changing my laptop's time to Wednesday at 7:50am and can confirm that it displays as "Closed now".
