### ISSUE TITLE
Open now returning No results have been found when there are 13 open results in search list

### ISSUE THREAD

**Issue by fredciaramaglia** [ShelterTechSF/askdarcel-web#779]
Run on staging: https://staging.askdarcel.org/search?refinementList%5Bcategories%5D%5B0%5D=Basic%20Needs%20%26%20Shelter&refinementList%5Bopen_times%5D%5B0%5D=W-09%3A00

Run Weds 6/19 at 9:10am

1. From home page click on 'Basic Needs & Shelter' button
Note that there are 18 items in the list and 13 of them are open (screen shot 1)
![image.png](https://images.zenhubusercontent.com/5cdcbb3d22376b7717f71776/2990a542-96d4-4c50-bfd1-116fbc2467bb)
2. Click on Open now button
No results found for (screen shot 2)
![image.png](https://images.zenhubusercontent.com/5cdcbb3d22376b7717f71776/dfd835d3-5ecf-4b8f-ab5f-72c727526a8e)

**Comment by richardxia** [comment]
The active refactoring I'm doing on the search results page should address this, so I'm actively working on this.

**Comment by fredciaramaglia** [comment]
Fixed by Richard's work on the search results page.
