### ISSUE TITLE
Landing Page Eligibility section updates

### ISSUE THREAD

**Issue by fredciaramaglia** [ShelterTechSF/askdarcel-web#780]
2 part adjustment of Discover Resources by Eligibility on the home page:

**- Add all 11 Eligibilities**
To facilitate exploratory discovery, MOHCD has asked for all 11 eligibilities we use as our narrowed down filters categories to be included in this section.

**- In addition, fix bug where the count next to each eligibility don't match the actual number of resources returned by each search** 
If you look at the Discover resources by eligibility section on the home page, each button has a count of entries to the right of the eligibility.  If you click on one of them and look at the results, the number of resources returned is less than the number in the button.

For example, clicking on 'Re-Entry   14' returns 10 resources.
(Run on staging 1.19) 

Suggestion:  Not a big deal, but since none of the buttons in other sections have counts, just remove the numbers from these buttons.

_(edited by @Maxastuart on 25-07-2019)_

**Comment by Maxastuart** [comment]
I just made some pretty major changes to search results, see if this works now

**Comment by derekfidler** [comment]
Addressed by #845
