### ISSUE TITLE
Use new time-related fields on calls to add/modify schedule days

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#788]
We added four new fields (open_time, open_day, close_time, close_day) to schedule days to better able to handle the case where a service or organization is open past midnight. Update the pages responsible for sending in schedule day change requests to use these new fields.

**Comment by richardxia** [comment]
Closing as wontdo, since it'll be a lot of work, and the edit page historically hasn't had many issues with time representations.
