### ISSUE TITLE
Implement the second field in the search bar.

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#80]

**Comment by derekfidler** [comment]
The second field (labeled Near Me) allows the user to put in an address, zipcode, or city to search from instead of using gps location. if location is disabled then this field should display a permission error and be required. I can add a comp for that case.

**Comment by jjfreund** [comment]
Fair enough. Then it seems to be unimplemented.

**Comment by lelandg559** [comment]
Question on this.

So to cover the three options presented there, putting in an address, zipcode, or city, I want to clarify the behavior.

1. Address: convert to GPS and treat it like we already do with GPS and just sort by that location.
2. Zipcode: filter results to only include that zipcode and sort based on ?
3. City: filter results to only include that city and sort based on ?
