### ISSUE TITLE
When building Docker images, start from previously built image

### ISSUE THREAD

**Issue by richardxia** [ShelterTechSF/askdarcel-web#804]
Our Docker images don't do any caching of previously built images, resulting in very large images. We can start from a previously built image and reuse layers of the Docker image, such as the parts that install Ubuntu packages.

This can be done by updating our Travis CI build scripts to 1) first pull the previously built image and 2) adding the `--cache-from` flag to the [`docker build`](https://docs.docker.com/engine/reference/commandline/build/) command.

**Comment by Maxastuart** [comment]
Should be done when migrating from TravisCI to GitHubActions
