### ISSUE TITLE
Add hours back to search results

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#840]
The new simplified search results look great! However, the hours are no longer displayed -- can we add those back in?

**Comment by derekfidler** [comment]
weird. not sure when that change happened. it was not part of my branch. just checked out the video i made before the PR was merged to master and they're definitely there. 
<img width="634" alt="Screen Shot 2019-08-25 at 20 18 21" src="https://user-images.githubusercontent.com/2722783/63654074-ba2b1f00-c775-11e9-9fad-9ccd3bf48a66.png">

**Comment by derekfidler** [comment]
fixed by #846
